server:
  address: ":8080"
  mode: "debug"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "your-password"
  dbname: "your-dbname"

jwt:
  secret: "your-secret-key"
  expiresIn: 86400
