basePath: /api/v1
definitions:
  handler.ChangePasswordRequest:
    properties:
      newPassword:
        minLength: 6
        type: string
      oldPassword:
        minLength: 6
        type: string
    required:
    - newPassword
    - oldPassword
    type: object
  handler.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  handler.LoginResponse:
    properties:
      tokenInfo:
        allOf:
        - $ref: '#/definitions/handler.TokenInfo'
        description: Token信息
      userInfo:
        allOf:
        - $ref: '#/definitions/handler.User'
        description: 用户信息
    type: object
  handler.RegisterRequest:
    properties:
      password:
        maxLength: 50
        minLength: 8
        type: string
      username:
        maxLength: 50
        minLength: 3
        type: string
    required:
    - password
    - username
    type: object
  handler.RegisterResponse:
    properties:
      userInfo:
        allOf:
        - $ref: '#/definitions/handler.User'
        description: 用户信息
    type: object
  handler.Response:
    properties:
      code:
        description: 响应码
        type: integer
      data:
        description: 响应数据
      message:
        description: 响应信息
        type: string
    type: object
  handler.TokenInfo:
    properties:
      createdAt:
        description: 创建时间
        type: string
      expiredAt:
        description: 过期时间
        type: string
      expiresIn:
        description: 有效时长(秒)
        type: integer
      token:
        description: JWT token
        type: string
    type: object
  handler.UpdateUserRequest:
    properties:
      avatar:
        description: 头像URL
        type: string
      bio:
        description: 用户简介
        type: string
      email:
        description: 邮箱
        type: string
      gender:
        description: 性别
        type: string
      location:
        description: 位置
        type: string
      mobile:
        description: 手机号
        type: string
      nickname:
        description: 用户昵称
        type: string
    type: object
  handler.User:
    properties:
      username:
        type: string
    type: object
  handler.UserDetailResponse:
    properties:
      avatar:
        type: string
      bio:
        type: string
      birthday:
        type: string
      email:
        type: string
      gender:
        type: string
      id:
        type: integer
      lastLogin:
        type: string
      location:
        description: 位置
        type: string
      mobile:
        description: 手机号
        type: string
      nickname:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  description: DDUP 服务 API 文档
  title: DDUP API
  version: "1.0"
paths:
  /health:
    get:
      description: 检查服务和数据库连接状态
      produces:
      - application/json
      responses:
        "200":
          description: 服务正常
          schema:
            $ref: '#/definitions/handler.Response'
        "503":
          description: 服务异常
          schema:
            $ref: '#/definitions/handler.Response'
      summary: 健康检查
      tags:
      - 系统
  /login:
    post:
      consumes:
      - application/json
      description: 用户登录
      parameters:
      - description: 登录信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功
          schema:
            allOf:
            - $ref: '#/definitions/handler.Response'
            - properties:
                data:
                  $ref: '#/definitions/handler.LoginResponse'
              type: object
        "400":
          description: 无效的请求参数
          schema:
            $ref: '#/definitions/handler.Response'
        "401":
          description: 用户名或密码错误
          schema:
            $ref: '#/definitions/handler.Response'
      summary: 用户登录
  /logout:
    post:
      consumes:
      - application/json
      description: 用户退出登录
      produces:
      - application/json
      responses:
        "200":
          description: 退出成功
          schema:
            $ref: '#/definitions/handler.Response'
        "401":
          description: 未授权
          schema:
            $ref: '#/definitions/handler.Response'
      security:
      - Bearer: []
      summary: 用户退出
  /register:
    post:
      consumes:
      - application/json
      description: 用户注册
      parameters:
      - description: 注册信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 注册成功
          schema:
            allOf:
            - $ref: '#/definitions/handler.Response'
            - properties:
                data:
                  $ref: '#/definitions/handler.RegisterResponse'
              type: object
        "400":
          description: 无效的请求参数
          schema:
            $ref: '#/definitions/handler.Response'
      summary: 用户注册
  /user:
    delete:
      consumes:
      - application/json
      description: 软除用户账号
      produces:
      - application/json
      responses:
        "200":
          description: 删除成功
          schema:
            $ref: '#/definitions/handler.Response'
        "401":
          description: 未授权
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: 系统错误
          schema:
            $ref: '#/definitions/handler.Response'
      security:
      - Bearer: []
      summary: 删除用户
    get:
      consumes:
      - application/json
      description: 获取用户详细信息（仅允许获取自己的信息）
      produces:
      - application/json
      responses:
        "200":
          description: 获取成功
          schema:
            allOf:
            - $ref: '#/definitions/handler.Response'
            - properties:
                data:
                  $ref: '#/definitions/handler.UserDetailResponse'
              type: object
        "401":
          description: 未授权
          schema:
            $ref: '#/definitions/handler.Response'
        "403":
          description: 禁止访问
          schema:
            $ref: '#/definitions/handler.Response'
      security:
      - Bearer: []
      summary: 获取用户详情
    put:
      consumes:
      - application/json
      description: 更新用户基本信息
      parameters:
      - description: 用户信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 更新成功
          schema:
            $ref: '#/definitions/handler.Response'
        "400":
          description: 无效的请求参数
          schema:
            $ref: '#/definitions/handler.Response'
        "401":
          description: 未授权
          schema:
            $ref: '#/definitions/handler.Response'
      security:
      - Bearer: []
      summary: 更新用户信息
  /user/password:
    put:
      consumes:
      - application/json
      description: 用户修改密码
      parameters:
      - description: 修改密码请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.ChangePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 密码修改成功
          schema:
            $ref: '#/definitions/handler.Response'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/handler.Response'
        "401":
          description: 未授权
          schema:
            $ref: '#/definitions/handler.Response'
      security:
      - Bearer: []
      summary: 修改密码
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
